// frontend/src/lib/indianLocations.js

export const locations = [
  // Major Cities (Top Tier)
  { value: "Mumbai, Maharashtra", label: "Mumbai, Maharashtra" },
  { value: "Delhi, NCT", label: "Delhi, NCT" }, // Keep this one
  { value: "Bengaluru, Karnataka", label: "Bengaluru, Karnataka" },
  { value: "Hyderabad, Telangana", label: "Hyderabad, Telangana" },
  { value: "Chennai, Tamil Nadu", label: "Chennai, Tamil Nadu" },
  { value: "Kolkata, West Bengal", label: "Kolkata, West Bengal" },
  { value: "Pune, Maharashtra", label: "Pune, Maharashtra" },
  { value: "Ahmedabad, Gujarat", label: "Ahmedabad, Gujarat" },
  { value: "Jaipur, Rajasthan", label: "Jaipur, Rajasthan" },
  { value: "Surat, Gujarat", label: "Surat, Gujarat" },
  { value: "Lucknow, Uttar Pradesh", label: "Lucknow, Uttar Pradesh" },
  { value: "Kanpur, Uttar Pradesh", label: "Kanpur, Uttar Pradesh" },
  { value: "Nagpur, Maharashtra", label: "Nagpur, Maharashtra" },
  { value: "Indore, Madhya Pradesh", label: "Indore, Madhya Pradesh" },
  { value: "Thane, Maharashtra", label: "Thane, Maharashtra" },
  { value: "Bhopal, Madhya Pradesh", label: "Bhopal, Madhya Pradesh" },
  { value: "Visakhapatnam, Andhra Pradesh", label: "Visakhapatnam, Andhra Pradesh" },
  { value: "Patna, Bihar", label: "Patna, Bihar" },
  { value: "Vadodara, Gujarat", label: "Vadodara, Gujarat" },
  { value: "Ludhiana, Punjab", label: "Ludhiana, Punjab" },
  { value: "Agra, Uttar Pradesh", label: "Agra, Uttar Pradesh" },
  { value: "Nashik, Maharashtra", label: "Nashik, Maharashtra" },
  { value: "Faridabad, Haryana", label: "Faridabad, Haryana" },
  { value: "Meerut, Uttar Pradesh", label: "Meerut, Uttar Pradesh" },
  { value: "Rajkot, Gujarat", label: "Rajkot, Gujarat" },
  { value: "Varanasi, Uttar Pradesh", label: "Varanasi, Uttar Pradesh" },
  { value: "Srinagar, Jammu & Kashmir", label: "Srinagar, Jammu & Kashmir" },
  { value: "Amritsar, Punjab", label: "Amritsar, Punjab" },
  { value: "Allahabad, Uttar Pradesh", label: "Allahabad, Uttar Pradesh" },
  { value: "Jodhpur, Rajasthan", label: "Jodhpur, Rajasthan" },
  { value: "Coimbatore, Tamil Nadu", label: "Coimbatore, Tamil Nadu" },
  { value: "Vijayawada, Andhra Pradesh", label: "Vijayawada, Andhra Pradesh" },
  { value: "Madurai, Tamil Nadu", label: "Madurai, Tamil Nadu" },
  { value: "Guwahati, Assam", label: "Guwahati, Assam" },
  { value: "Chandigarh, Chandigarh", label: "Chandigarh, Chandigarh" },
  { value: "Kochi, Kerala", label: "Kochi, Kerala" },
  { value: "Dehradun, Uttarakhand", label: "Dehradun, Uttarakhand" },
  { value: "Mysuru, Karnataka", label: "Mysuru, Karnataka" },
  { value: "Shimla, Himachal Pradesh", label: "Shimla, Himachal Pradesh" },
  { value: "Bhubaneswar, Odisha", label: "Bhubaneswar, Odisha" },
  { value: "Ranchi, Jharkhand", label: "Ranchi, Jharkhand" },

  // All States & Union Territories (Removed Delhi duplicate)
  { value: "Andaman & Nicobar Islands", label: "Andaman & Nicobar Islands" },
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Dadra & Nagar Haveli and Daman & Diu", label: "Dadra & Nagar Haveli and Daman & Diu" },
  // { value: "Delhi, NCT", label: "Delhi, NCT" }, // <-- REMOVED DUPLICATE
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jammu & Kashmir", label: "Jammu & Kashmir" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Lakshadweep", label: "Lakshadweep" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
].sort((a, b) => a.label.localeCompare(b.label)); // Alphabetize the list